### ISSUE TITLE
Instructions for standalone version of 3D-DART

### ISSUE THREAD

**Issue by mlowe308** [haddocking/3D-DART#2]
Thank you for sending me your software folders. I was able to install 3D-DART on my Mac, however jobnr8-PDBeditor was not created. What is the reason? I now need instructions for running 3D-DART. How do I specify the parameters? In the examples shown in https://haddock.science.uu.nl/dna/DARTusage.html#introduction, under "Download Results,"
I do not see a parameter file that matches the description on the website.

A couple of comments that might help the next person who wishes to install the standalone version of 3D-DART:
1. When installing the X3DNA files, you need version 1.5. These must be obtained directly from Xiang-Jun Lu.
2. In the bin directory, you must include EnergyPDNA.exe. This is a 3D-DART file, not X3DNA. The source code and header must be obtained from Brian Jimenez-Garcia.

**Comment by brianjimenez** [comment]
Is the folder `jobnr8-PDBeditor` not being created for the example provided in this repository?

**Comment by mlowe308** [comment]
I looked more carefully at the directories that were constructed using your repository. The directory names that were created do not match the ones listed on https://github.com/haddocking/3D-DART. Directory jobnr7-PDBeditor was created. There is no jobnr8-PDBeditor.

If I pick a random pdb file in jobnr7-PDBeditor, the DNA is not complete; for example it may only consist of one strand with bases and just the sugar-phosphate backbone of the other strand with no bases. Can you provide instructions on how to run the standalone version of 3D-DART? In the example, what should I expect to see?

**Comment by brianjimenez** [comment]
I confirm that in the example there is no ` jobnr8-PDBeditor`, that is dependent of the actual workflow used by 3D-DART. Indeed, the folder description is from a different example, so maybe documentation should be modified accordingly.

I confirm the problem when generating the pdb structures in the last step. this is one of the structures with Pymol:

<img width="539" alt="dna" src="https://user-images.githubusercontent.com/4330278/83537780-51878480-a4f5-11ea-80ee-bb2f54f9e91f.png">

I'm not the original developer and I don't really have experience on the chemistry behind this problem, so I mention here @amjjbonvin and @marcvdijk which probably could give you a better insight of the problem.

Attached the output of running the example [dart.out.zip](https://github.com/haddocking/3D-DART/files/4718099/dart.out.zip):

```bash
./RunDART.py -w NAensemblebuild -f example/struct_*.pdb > dart.out 2>&1
```

**Comment by amjjbonvin** [comment]
I would not worry about the way pymol displays the structure.

This is software-dependent. I sticks representation might give a better picture.

Also when introducing bends, distortions will be present.
Those models are usually meant to be refined.
